### ISSUE TITLE
Improvements to install process?

### ISSUE THREAD

**Issue by gingerbeardman** [thestr4ng3r/mymcplus#1]
I get
```
$ pip install mymcplus[GUI]
Collecting mymcplus[GUI]
  Ignoring wxPython: markers 'extra == "GUI"' don't match your environment
Installing collected packages: mymcplus
Successfully installed mymcplus-3.0.1
```

but
```
$ pip install wxPython
Requirement already satisfied: wxPython in /usr/local/lib/python3.6/site-packages (4.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from wxPython) (1.11.0)
```

Could you let me know how to proceed?

Forgive me as I'm not a Python user.

Thanks

**Comment by gingerbeardman** [comment]
Trying to run it anyway...
```
$ mymcplus ~/Desktop/cartridge.sram gui
Traceback (most recent call last):
  File "/usr/local/bin/mymcplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/mymcplus/mymc.py", line 771, in main
    subopt_parser.error)
  File "/usr/local/lib/python3.6/site-packages/mymcplus/mymc.py", line 454, in do_gui
    from .gui import gui
  File "/usr/local/lib/python3.6/site-packages/mymcplus/gui/gui.py", line 32, in <module>
    from .icon_window import IconWindow
  File "/usr/local/lib/python3.6/site-packages/mymcplus/gui/icon_window.py", line 24, in <module>
    from .icon_renderer import IconRenderer
  File "/usr/local/lib/python3.6/site-packages/mymcplus/gui/icon_renderer.py", line 20, in <module>
    from OpenGL.GL import *
ModuleNotFoundError: No module named 'OpenGL'
```

**Comment by gingerbeardman** [comment]
`easy_install pyopengl`

and I'm in :)

**Comment by thestr4ng3r** [comment]
> `Ignoring wxPython: markers 'extra == "GUI"' don't match your environment`

Seems like this is a bug in pip: https://github.com/pypa/pip/issues/4617. I'll rename the extra to lowercase gui.

> OpenGL should be added to the requirements file?

Yes, it should be added.

**Comment by thestr4ng3r** [comment]
New version 3.0.2 is now available.

**Comment by gingerbeardman** [comment]
Thanks!
