### ISSUE TITLE
Can't delete saves from the memory card

### ISSUE THREAD

**Issue by Bazatree** [thestr4ng3r/mymcplus#7]
The "delete" command doesn't work at all. It doesn't delete saves and throws errors to the terminal.
![memory](https://user-images.githubusercontent.com/12977268/86535359-68503b00-bee8-11ea-8dbd-b40d097f7e44.PNG)

Example file:
_Honestly, it doesn't matter what memory card image I am editing, but well, here is an example file:_
[TEST_GTASAv1.03_importedCBS.zip](https://github.com/thestr4ng3r/mymcplus/files/4875084/TEST_GTASAv1.03_importedCBS.zip)

**Comment by devinjustice** [comment]
I'm having the same issue. I had to go into PCSX2 and browse the memory card to easily delete a save file.

**Comment by duhow** [comment]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mymcplus/gui/gui.py", line 477, in evt_cmd_delete
    for i in selected]
  File "/usr/local/lib/python3.7/site-packages/mymcplus/gui/gui.py", line 477, in <listcomp>
    for i in selected]
TypeError: 'TableEntry' object is not subscriptable```
